-- 저장 함수(stored function)
CREATE OR REPLACE FUNCTION CAL_BONUS(VEMPNO IN EMP.EMPNO%TYPE)
    RETURN NUMBER --반환값 데이터타입
IS
    VSAL NUMBER(7,2); --지역변수 데이터타입
BEGIN
    SELECT SAL INTO VSAL
    FROM EMP
    WHERE EMPNO=VEMPNO;
    
    RETURN(VSAL*2); --반환값
END;
/

VARIABLE VAR_RES NUMBER; --바인드변수 데이터타입
EXECUTE : VAR_RES := CAL_BONUS(7788); --바인드변수 := 함수이름
PRINT VAR_RES;

--과제 : 사원명으로 검색하여 해당 사원의 직급을 얻어 오는 저장 함수를 SEL_EMPNAME02라는 이름으로 작성하라.
CREATE OR REPLACE FUNCTION SEL_EMPNAME02(VNAME IN EMP.ENAME%TYPE)
    RETURN VARCHAR2
IS
    VAR_JOB_RES VARCHAR2(9);
BEGIN
    SELECT JOB INTO VAR_JOB_RES
    FROM EMP
    WHERE ENAME=VNAME;
    
    RETURN VAR_JOB_RES;
END;
/

VARIABLE VAR_JOB VARCHAR2(9);
EXECUTE :VAR_JOB := SEL_EMPNAME02('SCOTT');
PRINT VAR_JOB;
    
