SHOW USER;

--GRANT CREATE TABLE TO SOCTT; --SCOTT이 TABLE을 만들 수 있게 권한을준다.
--GRANT CONNECT, RESOURCE TO SCOTT;
--REVOKE CREATE TABLE FROM SCOTT; --SCOTT이 TABLE을 만들 수 없게 권한을 취소한다.
--REVOKE CONNECT, RESOURCE FROM SCOTT;

